docker run --rm \
  --name=weatherflow-collector-LOlympus-remote-import \
  -e TZ=America/Denver \
  -e WEATHERFLOW_COLLECTOR_COLLECTOR_TYPE=remote-import \
  -e WEATHERFLOW_COLLECTOR_DEBUG=false \
  -e WEATHERFLOW_COLLECTOR_DEBUG_CURL=false \
  -e WEATHERFLOW_COLLECTOR_FUNCTION=import \
  -e WEATHERFLOW_COLLECTOR_HEALTHCHECK=true \
  -e WEATHERFLOW_COLLECTOR_HOST_HOSTNAME=MBP.olympusdrive.com \
  -e WEATHERFLOW_COLLECTOR_IMPORT_DAYS=10 \
  -e WEATHERFLOW_COLLECTOR_INFLUXDB_PASSWORD=x8egQTrf4bGl8Cs3XGyF1yE0b06pfgJe \
  -e WEATHERFLOW_COLLECTOR_INFLUXDB_URL=http://MBP.olympusdrive.com:8086/write?db=weatherflow \
  -e WEATHERFLOW_COLLECTOR_INFLUXDB_USERNAME=weatherflow \
  -e WEATHERFLOW_COLLECTOR_STATION_ID="193316" \
  -e WEATHERFLOW_COLLECTOR_THREADS=4 \
  -e WEATHERFLOW_COLLECTOR_TOKEN=a1af9766-cf15-429b-8bbc-8c40bcda2314 \
  lux4rd0/weatherflow-collector:latest


