apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weatherflow

bases:
  - ../../base

images:
  - name: registry.olympusdrive.com/weatherflow-collector
    newTag: latest

commonLabels:
  environment: production
