apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: weatherflow
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
    name: http
  selector:
    app: influxdb
